// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVFelXbR624iJJAK6RTVXIwYX_aP_ns8',
    appId: '1:2239947884:web:94e295825cd4521ec3e449',
    messagingSenderId: '2239947884',
    projectId: 'flutterloginregister-f63ad',
    authDomain: 'flutterloginregister-f63ad.firebaseapp.com',
    storageBucket: 'flutterloginregister-f63ad.firebasestorage.app',
    measurementId: 'G-Z9WWWMHEFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ThAh9WzNidyYL8pVQm9fTzqa7S5iLFs',
    appId: '1:2239947884:android:1b82a420555b6c25c3e449',
    messagingSenderId: '2239947884',
    projectId: 'flutterloginregister-f63ad',
    storageBucket: 'flutterloginregister-f63ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv7t9gY9PktPffL-9niM1wvbyjWwyIT_M',
    appId: '1:2239947884:ios:899540b9836c56b7c3e449',
    messagingSenderId: '2239947884',
    projectId: 'flutterloginregister-f63ad',
    storageBucket: 'flutterloginregister-f63ad.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv7t9gY9PktPffL-9niM1wvbyjWwyIT_M',
    appId: '1:2239947884:ios:899540b9836c56b7c3e449',
    messagingSenderId: '2239947884',
    projectId: 'flutterloginregister-f63ad',
    storageBucket: 'flutterloginregister-f63ad.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnVFelXbR624iJJAK6RTVXIwYX_aP_ns8',
    appId: '1:2239947884:web:4fac71d9ec9a10b2c3e449',
    messagingSenderId: '2239947884',
    projectId: 'flutterloginregister-f63ad',
    authDomain: 'flutterloginregister-f63ad.firebaseapp.com',
    storageBucket: 'flutterloginregister-f63ad.firebasestorage.app',
    measurementId: 'G-DVF56FCSVB',
  );
}
