// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvkUkzWHMjNO9lQJF3BZyQUYYqawXxrgk',
    appId: '1:232411408300:web:c31e6563daa1205fea3c09',
    messagingSenderId: '232411408300',
    projectId: 'denemeg-59bfe',
    authDomain: 'denemeg-59bfe.firebaseapp.com',
    storageBucket: 'denemeg-59bfe.firebasestorage.app',
    measurementId: 'G-J6KPVEP6VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0sU64Zdq6eNB96c8-bSObz5mwtZQBkQ',
    appId: '1:232411408300:android:2448e8436547d811ea3c09',
    messagingSenderId: '232411408300',
    projectId: 'denemeg-59bfe',
    storageBucket: 'denemeg-59bfe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvkUkzWHMjNO9lQJF3BZyQUYYqawXxrgk',
    appId: '1:232411408300:web:2d1d42f953f511f2ea3c09',
    messagingSenderId: '232411408300',
    projectId: 'denemeg-59bfe',
    authDomain: 'denemeg-59bfe.firebaseapp.com',
    storageBucket: 'denemeg-59bfe.firebasestorage.app',
    measurementId: 'G-4YTGLCHG5X',
  );
}
